from decimal import Decimal
from django.conf import settings
from django.db import models


class Payment(models.Model):
    """
    Model representing Razorpay payment transaction associated with an Order.
    Tracks gateway order IDs, verification signatures, monetary amounts, and lifecycle status.
    """

    class PaymentStatus(models.TextChoices):
        PENDING = "PENDING", "Pending"
        CREATED = "CREATED", "Created"
        PAID = "PAID", "Paid"
        FAILED = "FAILED", "Failed"
        CANCELLED = "CANCELLED", "Cancelled"
        REFUNDED = "REFUNDED", "Refunded"

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="payments",
        db_index=True,
        help_text="Authenticated customer initiating the payment",
    )
    order = models.OneToOneField(
        "orders.Order",
        on_delete=models.CASCADE,
        related_name="payment",
        db_index=True,
        help_text="Associated order for this payment transaction",
    )
    razorpay_order_id = models.CharField(
        max_length=100,
        blank=True,
        null=True,
        db_index=True,
        help_text="Order ID returned by Razorpay API",
    )
    razorpay_payment_id = models.CharField(
        max_length=100,
        blank=True,
        null=True,
        db_index=True,
        help_text="Payment ID captured by Razorpay upon successful checkout",
    )
    razorpay_signature = models.CharField(
        max_length=255,
        blank=True,
        null=True,
        help_text="Cryptographic signature generated by Razorpay for authentication verification",
    )
    amount = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        default=Decimal("0.00"),
        help_text="Transaction amount in major currency units (e.g. INR)",
    )
    currency = models.CharField(
        max_length=10,
        default="INR",
        help_text="Three-letter ISO currency code (defaults to INR)",
    )
    status = models.CharField(
        max_length=20,
        choices=PaymentStatus.choices,
        default=PaymentStatus.PENDING,
        db_index=True,
        help_text="Lifecycle payment status",
    )
    failure_reason = models.TextField(
        blank=True,
        default="",
        help_text="Detailed error description or reason if payment failed",
    )
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]
        verbose_name = "Payment"
        verbose_name_plural = "Payments"
        indexes = [
            models.Index(fields=["razorpay_order_id"], name="idx_payment_rzp_order_id"),
            models.Index(fields=["status"], name="idx_payment_status"),
            models.Index(fields=["created_at"], name="idx_payment_created_at"),
        ]

    def __str__(self):
        return f"Payment #{self.id} - Order #{self.order_id} ({self.status}) - {self.currency} {self.amount}"

    @property
    def amount_in_subunits(self) -> int:
        """Returns the amount converted to smallest currency subunit (paise) for Razorpay API."""
        return int(Decimal(self.amount * 100).quantize(Decimal("1")))
