# Generated by Django 5.2.17 on 2026-09-03 17:04

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(blank=True, db_index=True, help_text='Order ID returned by Razorpay API', max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, db_index=True, help_text='Payment ID captured by Razorpay upon successful checkout', max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, help_text='Cryptographic signature generated by Razorpay for authentication verification', max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Transaction amount in major currency units (e.g. INR)', max_digits=12)),
                ('currency', models.CharField(default='INR', help_text='Three-letter ISO currency code (defaults to INR)', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CREATED', 'Created'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', help_text='Lifecycle payment status', max_length=20)),
                ('failure_reason', models.TextField(blank=True, default='', help_text='Detailed error description or reason if payment failed')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(help_text='Associated order for this payment transaction', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
                ('user', models.ForeignKey(help_text='Authenticated customer initiating the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['razorpay_order_id'], name='idx_payment_rzp_order_id'), models.Index(fields=['status'], name='idx_payment_status'), models.Index(fields=['created_at'], name='idx_payment_created_at')],
            },
        ),
    ]
