# Generated by Django 5.2.17 on 2026-09-03 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Recipient full name', max_length=255)),
                ('phone_number', models.CharField(blank=True, default='', help_text='Contact phone number', max_length=30)),
                ('street_address', models.CharField(help_text='Street address / line 1', max_length=255)),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('state', models.CharField(blank=True, default='', help_text='State / Province / Region', max_length=100)),
                ('postal_code', models.CharField(help_text='Postal / ZIP code', max_length=30)),
                ('country', models.CharField(help_text='Country', max_length=100)),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default shipping address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns this address', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
