# Generated by Django 5.2.17 on 2026-09-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique category name', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Category description')),
                ('image', models.ImageField(blank=True, help_text='Category banner or representative image', null=True, upload_to='categories/')),
                ('icon', models.CharField(blank=True, default='', help_text='Icon identifier for frontend rendering', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether category is active and visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
    ]
