# Generated by Django 5.2.17 on 2026-09-03 11:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_product_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, editable=False, help_text='Unique public order reference number (e.g. ORD-12345)', max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Current processing status of the order', max_length=32)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all order item subtotals', max_digits=12)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Shipping and handling charges', max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated tax amount', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Grand total payable (subtotal + shipping + tax)', max_digits=12)),
                ('payment_method', models.CharField(blank=True, default='Credit Card', help_text='Selected payment method (e.g. card, cod, Apple Pay)', max_length=64)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='paid', help_text='Payment state for this order', max_length=32)),
                ('tracking_number', models.CharField(blank=True, default='', help_text='Carrier shipment tracking identifier', max_length=64)),
                ('estimated_delivery', models.DateField(blank=True, help_text='Estimated delivery date for shipment', null=True)),
                ('shipping_full_name', models.CharField(help_text='Recipient full name captured at checkout', max_length=255)),
                ('shipping_phone', models.CharField(blank=True, default='', help_text='Recipient phone number captured at checkout', max_length=50)),
                ('shipping_address_line1', models.CharField(help_text='Street address line 1 captured at checkout', max_length=255)),
                ('shipping_address_line2', models.CharField(blank=True, default='', help_text='Apartment, suite, unit, etc. captured at checkout', max_length=255)),
                ('shipping_city', models.CharField(help_text='City captured at checkout', max_length=100)),
                ('shipping_state', models.CharField(blank=True, default='', help_text='State / Province captured at checkout', max_length=100)),
                ('shipping_postal_code', models.CharField(help_text='Postal / ZIP code captured at checkout', max_length=30)),
                ('shipping_country', models.CharField(default='United States', help_text='Country captured at checkout', max_length=100)),
                ('notes', models.TextField(blank=True, default='', help_text='Optional customer order instructions or delivery notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Authenticated customer who placed this order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Product title / name snapshot at time of purchase', max_length=255)),
                ('product_sku', models.CharField(blank=True, default='', help_text='Product SKU snapshot', max_length=100)),
                ('product_image_url', models.CharField(blank=True, default='', help_text='Product primary image URL snapshot', max_length=500)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per single unit snapshot at time of checkout', max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Purchased quantity')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Item total price (unit_price * quantity)', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(help_text='Order this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(blank=True, help_text='Reference to original product catalog entry (nullable if product deleted)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ['id'],
            },
        ),
    ]
