# Generated by Django 5.2.17 on 2026-09-03 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product title / name', max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Detailed product description')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, help_text='Selling price', max_digits=10)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original or compare-at price before discount', max_digits=10, null=True)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Available stock quantity')),
                ('brand', models.CharField(blank=True, default='', help_text='Product brand / manufacturer', max_length=100)),
                ('sku', models.CharField(blank=True, default='', help_text='Stock Keeping Unit', max_length=100)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating score (0.00 - 5.00)', max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0, help_text='Total number of customer reviews')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether product is active and visible')),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Whether product is featured on home/promos')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Primary category for this product', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Uploaded product image file', upload_to='products/')),
                ('alt_text', models.CharField(blank=True, default='', help_text='Descriptive alt text for accessibility and SEO', max_length=255)),
                ('is_primary', models.BooleanField(default=False, help_text='Flag indicating whether this is the main product thumbnail')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order in which images appear in gallery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(help_text='Product this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
